### ISSUE TITLE
CHECKBOX FRAMEWORK unsupported framework - URGENT!

### ISSUE THREAD

**Issue by siddharthadeb** [chrisamanse/CheckboxButton#4]
Unable upload to iTunes connect- Checkboxbutton framework showed unsupported framework-
Please help ,urgent!

![screen shot 2017-07-14 at 6 00 00 pm](https://user-images.githubusercontent.com/1187989/28236743-8762312e-694b-11e7-886b-b0764fecc3a1.png)
![screen shot 2017-07-14 at 5 59 43 pm](https://user-images.githubusercontent.com/1187989/28236748-be2185fc-694b-11e7-8e4f-9b69a222668a.png)

![screen shot 2017-07-14 at 5 59 50 pm](https://user-images.githubusercontent.com/1187989/28236745-896585b6-694b-11e7-8a41-dc1a3cd660fb.png)

**Comment by chrisamanse** [comment]
What Xcode version are you using? And how are you importing it to your project? For a quick fix, manually copy `CheckboxButton.swift` to your project.

**Comment by siddharthadeb** [comment]
Xcode 8 (latest) - importing manually CheckboxButton.framework to build.
