### ISSUE TITLE
Cannot change class of UIButton to CheckboxButton in Interface Builder 9.3

### ISSUE THREAD

**Issue by paulw11** [chrisamanse/CheckboxButton#6]
The documentation states that you can change a `UIButton` to `CheckboxButton` in Interface Builder, but as of 9.3 this does not seem to be possible.

`UIControl` is a superclass of `UIButton`, but Interface Builder does not let you substitute a class that is not a subclass of the object you have placed.  Changing `CheckboxButton` to subclass `UIButton` resolves this issue.

Otherwise, you must place a `UIView` in the storyboard scene and change its class to `CheckboxButton`

**Comment by chrisamanse** [comment]
You are right, to use in Interface Builder, the view component in the storyboard needs to be `UIView`, not a `UIButton`. Thanks for reporting the inaccuracy of the docs, I'll update it
